// ==========================================================================
// DO NOT EDIT - generated by tools/gen_abi.py from abi/drawgui.def.toml.
//
// Edit abi/drawgui.def.toml and re-run:
//     python3 tools/gen_abi.py
// `python3 tools/gen_abi.py --check` fails when this file has drifted.
// ==========================================================================

// Every exported symbol below is generated: design.md section 5.17.1
// forbids a hand-written export function, because a hand-written one
// is the one a person forgets to wrap. `dg::abi::<impl>` (src/abi/
// abi_impl.h/.cpp) is hand-written and free to throw; everything in
// THIS file exists only to make that safe to cross into C from.

#include "drawgui/abi/drawgui.h"

#include <new>
#include <stdexcept>
#include <string>

#include "abi_impl.h"

extern "C" DG_EXPORT uint32_t dg_abi_version(void) {
  try {
    return dg::abi::abi_version();
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_abi_version: out of memory");
    return 0;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_abi_version: ") + e.what());
    return 0;
  } catch (...) {
    dg::abi::set_last_error("dg_abi_version: unknown exception");
    return 0;
  }
}

extern "C" DG_EXPORT dg_app_t* dg_app_create(const dg_app_opts* opts) {
  try {
    return dg::abi::app_create(opts);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_app_create: out of memory");
    return nullptr;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_app_create: ") + e.what());
    return nullptr;
  } catch (...) {
    dg::abi::set_last_error("dg_app_create: unknown exception");
    return nullptr;
  }
}

extern "C" DG_EXPORT void dg_app_destroy(dg_app_t* app) {
  try {
    dg::abi::app_destroy(app);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_app_destroy: out of memory");
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_app_destroy: ") + e.what());
  } catch (...) {
    dg::abi::set_last_error("dg_app_destroy: unknown exception");
  }
}

extern "C" DG_EXPORT dg_window_t* dg_window_create(dg_app_t* app, const dg_window_opts* opts) {
  try {
    return dg::abi::window_create(app, opts);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_window_create: out of memory");
    return nullptr;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_window_create: ") + e.what());
    return nullptr;
  } catch (...) {
    dg::abi::set_last_error("dg_window_create: unknown exception");
    return nullptr;
  }
}

extern "C" DG_EXPORT int32_t dg_window_set_root(dg_window_t* window, dg_node_t* node) {
  try {
    return dg::abi::window_set_root(window, node);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_window_set_root: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_window_set_root: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_window_set_root: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT dg_node_t* dg_node_create(dg_app_t* app, uint16_t type_id) {
  try {
    return dg::abi::node_create(app, type_id);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_node_create: out of memory");
    return nullptr;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_node_create: ") + e.what());
    return nullptr;
  } catch (...) {
    dg::abi::set_last_error("dg_node_create: unknown exception");
    return nullptr;
  }
}

extern "C" DG_EXPORT int32_t dg_node_set_prop(dg_node_t* node, uint16_t prop_id,
                                              const dg_value* value) {
  try {
    return dg::abi::node_set_prop(node, prop_id, value);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_node_set_prop: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_node_set_prop: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_node_set_prop: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT int32_t dg_node_insert_before(dg_node_t* parent, dg_node_t* child,
                                                   dg_node_t* ref) {
  try {
    return dg::abi::node_insert_before(parent, child, ref);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_node_insert_before: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_node_insert_before: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_node_insert_before: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT int32_t dg_node_remove(dg_node_t* node) {
  try {
    return dg::abi::node_remove(node);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_node_remove: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_node_remove: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_node_remove: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT int32_t dg_wait_events(dg_app_t* app, int32_t timeout_ms) {
  try {
    return dg::abi::wait_events(app, timeout_ms);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_wait_events: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_wait_events: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_wait_events: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT int32_t dg_poll_events(dg_app_t* app, dg_event* out, int32_t max) {
  try {
    return dg::abi::poll_events(app, out, max);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_poll_events: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_poll_events: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_poll_events: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT const char* dg_last_error(void) {
  try {
    return dg::abi::last_error();
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_last_error: out of memory");
    return nullptr;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_last_error: ") + e.what());
    return nullptr;
  } catch (...) {
    dg::abi::set_last_error("dg_last_error: unknown exception");
    return nullptr;
  }
}

extern "C" DG_EXPORT const char* dg_dump_layout_tree(dg_node_t* node) {
  try {
    return dg::abi::dump_layout_tree(node);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_dump_layout_tree: out of memory");
    return nullptr;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_dump_layout_tree: ") + e.what());
    return nullptr;
  } catch (...) {
    dg::abi::set_last_error("dg_dump_layout_tree: unknown exception");
    return nullptr;
  }
}

extern "C" DG_EXPORT int32_t dg_debug_warp_pointer(dg_window_t* window, int32_t x, int32_t y) {
  try {
    return dg::abi::debug_warp_pointer(window, x, y);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_debug_warp_pointer: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_debug_warp_pointer: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_debug_warp_pointer: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT int32_t dg_debug_post_pointer_button(dg_window_t* window, int32_t down,
                                                          int32_t x, int32_t y) {
  try {
    return dg::abi::debug_post_pointer_button(window, down, x, y);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_debug_post_pointer_button: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_debug_post_pointer_button: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_debug_post_pointer_button: unknown exception");
    return DG_ERR_INTERNAL;
  }
}

extern "C" DG_EXPORT int32_t dg_debug_trigger_exception(int32_t kind) {
  try {
    return dg::abi::debug_trigger_exception(kind);
  } catch (const std::bad_alloc&) {
    dg::abi::set_last_error("dg_debug_trigger_exception: out of memory");
    return DG_ERR_OOM;
  } catch (const std::exception& e) {
    dg::abi::set_last_error(std::string("dg_debug_trigger_exception: ") + e.what());
    return DG_ERR_INTERNAL;
  } catch (...) {
    dg::abi::set_last_error("dg_debug_trigger_exception: unknown exception");
    return DG_ERR_INTERNAL;
  }
}
