// ==========================================================================
// DO NOT EDIT - generated by tools/gen_props.py from props/drawgui.props.toml.
//
// Edit props/drawgui.props.toml and re-run:
//     python3 tools/gen_props.py
// The build regenerates this file, and `python3 tools/gen_props.py --check`
// fails when it has drifted, so a stale copy cannot be committed.
// ==========================================================================

#pragma once

#include <cstdint>

// Property identifiers crossing the C ABI. Numeric, never strings: a frame
// may write thousands of properties and string hashing is pure waste
// (design.md section 5.8 decision 1).
//
// These values are an ABI contract. They are append-only and are never
// reused or renumbered; only a MAJOR version may break them
// (design.md section 5.8 decision 4).
enum dg_prop_id : std::uint16_t {
  // Reserved. A write with this id is always an error.
  DG_PROP_INVALID = 0,

  // -- box_model -------------------------------------------------
  // Border-box width; absent means shrink-to-fit.
  // type=length optional; applies_to=box
  DG_PROP_WIDTH = 1,
  // Border-box height; absent means shrink-to-fit.
  // type=length optional; applies_to=box
  DG_PROP_HEIGHT = 2,
  // Lower clamp applied after the size source resolves.
  // type=length; applies_to=box
  DG_PROP_MIN_WIDTH = 3,
  // Upper clamp applied after the size source resolves.
  // type=length; applies_to=box
  DG_PROP_MAX_WIDTH = 4,
  // Lower clamp applied after the size source resolves.
  // type=length; applies_to=box
  DG_PROP_MIN_HEIGHT = 5,
  // Upper clamp applied after the size source resolves.
  // type=length; applies_to=box
  DG_PROP_MAX_HEIGHT = 6,
  // width/height; derives the second dimension from the first.
  // type=float optional; applies_to=box
  DG_PROP_ASPECT_RATIO = 7,
  // Left padding; shrinks the constraint passed to children.
  // type=float; applies_to=box
  DG_PROP_PADDING_L = 8,
  // Top padding; shrinks the constraint passed to children.
  // type=float; applies_to=box
  DG_PROP_PADDING_T = 9,
  // Right padding; shrinks the constraint passed to children.
  // type=float; applies_to=box
  DG_PROP_PADDING_R = 10,
  // Bottom padding; shrinks the constraint passed to children.
  // type=float; applies_to=box
  DG_PROP_PADDING_B = 11,
  // Left outer spacing applied by the parent, excluded from size.
  // type=float; parentData scope=base consumed_by=flex,wrap,stack
  DG_PROP_MARGIN_L = 12,
  // Top outer spacing applied by the parent, excluded from size.
  // type=float; parentData scope=base consumed_by=flex,wrap,stack
  DG_PROP_MARGIN_T = 13,
  // Right outer spacing applied by the parent, excluded from size.
  // type=float; parentData scope=base consumed_by=flex,wrap,stack
  DG_PROP_MARGIN_R = 14,
  // Bottom outer spacing applied by the parent, excluded from size.
  // type=float; parentData scope=base consumed_by=flex,wrap,stack
  DG_PROP_MARGIN_B = 15,

  // -- visual ----------------------------------------------------
  // Border-box fill, 0xAARRGGBB unpremultiplied.
  // type=color; applies_to=box
  DG_PROP_BACKGROUND_COLOR = 16,
  // Linear/radial/sweep gradient fill; dedicated setter, not a scalar.
  // type=gradient optional; applies_to=box
  DG_PROP_BACKGROUND_GRADIENT = 17,
  // Left border thickness, inside the border box.
  // type=float; applies_to=box
  DG_PROP_BORDER_WIDTH_L = 18,
  // Top border thickness, inside the border box.
  // type=float; applies_to=box
  DG_PROP_BORDER_WIDTH_T = 19,
  // Right border thickness, inside the border box.
  // type=float; applies_to=box
  DG_PROP_BORDER_WIDTH_R = 20,
  // Bottom border thickness, inside the border box.
  // type=float; applies_to=box
  DG_PROP_BORDER_WIDTH_B = 21,
  // Colour of all four borders, 0xAARRGGBB unpremultiplied.
  // type=color; applies_to=box
  DG_PROP_BORDER_COLOR = 22,
  // Top-left corner radius; clips every decoration layer.
  // type=float; applies_to=box
  DG_PROP_BORDER_RADIUS_TL = 23,
  // Top-right corner radius; clips every decoration layer.
  // type=float; applies_to=box
  DG_PROP_BORDER_RADIUS_TR = 24,
  // Bottom-right corner radius; clips every decoration layer.
  // type=float; applies_to=box
  DG_PROP_BORDER_RADIUS_BR = 25,
  // Bottom-left corner radius; clips every decoration layer.
  // type=float; applies_to=box
  DG_PROP_BORDER_RADIUS_BL = 26,
  // 0..1 subtree alpha; below 1 forces a compositing layer.
  // type=float; applies_to=box
  DG_PROP_OPACITY = 27,
  // Outer shadow (offset/blur/spread/colour); dedicated setter.
  // type=shadow optional; applies_to=box
  DG_PROP_SHADOW = 28,
  // Whether content beyond the border box is clipped.
  // type=enum; applies_to=box
  // values: visible | clip
  DG_PROP_OVERFLOW = 29,
  // Decomposed translate/scale/rotate plus origin, for interpolation.
  // type=transform optional; applies_to=box
  DG_PROP_TRANSFORM = 30,

  // -- container -------------------------------------------------
  // Main axis orientation and ordering.
  // type=enum; applies_to=flex,wrap
  // values: row | column | row_reverse | column_reverse
  DG_PROP_DIRECTION = 31,
  // Distribution of free space along the main axis.
  // type=enum; applies_to=flex,wrap
  // values: start | end | center | space_between | space_around | space_evenly
  DG_PROP_JUSTIFY = 32,
  // Cross-axis alignment of children within a line.
  // type=enum; applies_to=flex,wrap
  // values: start | end | center | stretch | baseline
  DG_PROP_ALIGN = 33,
  // Main-axis spacing between adjacent children; adds to margins.
  // type=float; applies_to=flex,wrap
  DG_PROP_GAP = 34,
  // Whether the container hugs its content or fills the main axis.
  // type=enum; applies_to=flex,wrap
  // values: min | max
  DG_PROP_MAIN_SIZE = 35,
  // Spacing between wrapped runs; meaningful only on RenderWrap.
  // type=float; applies_to=wrap
  DG_PROP_RUN_GAP = 36,
  // Cross-axis alignment of the run stack; RenderWrap only.
  // type=enum; applies_to=wrap
  // values: start | end | center | stretch | space_between | space_around
  DG_PROP_ALIGN_CONTENT = 37,

  // -- parent_data -----------------------------------------------
  // Weight for distributing positive free main-axis space.
  // type=float; parentData scope=flex consumed_by=flex
  DG_PROP_GROW = 38,
  // Weight for absorbing negative free main-axis space.
  // type=float; parentData scope=flex consumed_by=flex
  DG_PROP_SHRINK = 39,
  // Main-axis base size; absent means the child's natural size.
  // type=float optional; parentData scope=flex consumed_by=flex
  DG_PROP_BASIS = 40,
  // Per-child override of the container's cross-axis align.
  // type=enum; parentData scope=flex consumed_by=flex
  // values: auto | start | end | center | stretch | baseline
  DG_PROP_ALIGN_SELF = 41,
  // Inset from the stack content box; setting it positions the child.
  // type=float optional; parentData scope=stack consumed_by=stack
  DG_PROP_LEFT = 42,
  // Inset from the stack content box; setting it positions the child.
  // type=float optional; parentData scope=stack consumed_by=stack
  DG_PROP_TOP = 43,
  // Inset from the stack content box; setting it positions the child.
  // type=float optional; parentData scope=stack consumed_by=stack
  DG_PROP_RIGHT = 44,
  // Inset from the stack content box; setting it positions the child.
  // type=float optional; parentData scope=stack consumed_by=stack
  DG_PROP_BOTTOM = 45,
};

// Highest id currently assigned. Boundary code uses it to reject out of
// range ids before dispatching; it grows as properties are appended.
inline constexpr std::uint16_t kDgPropMaxId = 45;

// Number of properties defined. Not an ABI value - retired ids leave gaps,
// so this is not the same as kDgPropMaxId.
inline constexpr std::uint16_t kDgPropCount = 45;
