// ==========================================================================
// DO NOT EDIT - generated by tools/gen_theme.py from themes/schema.toml.
//
// Edit themes/schema.toml and re-run:
//     python3 tools/gen_theme.py
// `python3 tools/gen_theme.py --check` fails when this file has drifted.
// ==========================================================================

#pragma once

namespace dg {

// Embedded verbatim from themes/builtin/theme.json.
inline constexpr char kBuiltinThemeJson[] = R"DGTHEMEJSON(
{
  "schema_version": 1,
  "name": "drawgui-builtin",
  "base": {
    "radius.sm": 4,
    "radius.md": 8,
    "space.sm": 4,
    "space.md": 8
  },
  "variants": {
    "light": {
      "color.surface": "#FFFFFFFF",
      "color.on-surface": "#1A1A1AFF",
      "color.border": "#C7CCD1FF",
      "color.primary": "#3366CCFF",
      "color.on-primary": "#FFFFFFFF",
      "color.primary-hover": "#4A78D6FF",
      "color.primary-pressed": "#2952A3FF",
      "color.focus-ring": "#FF8800FF"
    },
    "dark": {
      "color.surface": "#1E1E1EFF",
      "color.on-surface": "#E8E8E8FF",
      "color.border": "#3A3F45FF",
      "color.primary": "#6699FFFF",
      "color.on-primary": "#0D1117FF",
      "color.primary-hover": "#7FAAFFFF",
      "color.primary-pressed": "#5580D9FF",
      "color.focus-ring": "#FFA733FF"
    }
  }
}
)DGTHEMEJSON";

}  // namespace dg
