// ==========================================================================
// DO NOT EDIT - generated by tools/gen_theme.py from themes/schema.toml.
//
// Edit themes/schema.toml and re-run:
//     python3 tools/gen_theme.py
// `python3 tools/gen_theme.py --check` fails when this file has drifted.
// ==========================================================================

#pragma once

#include <cstdint>

// Theme token identifiers - the same shape as dg_prop_id
// (include/drawgui/render/prop_ids.generated.h), and for the identical
// reason: PLAIN CONSTANTS, NOT AN ENUMERATION. A token_id arrives from a
// theme.json's string name via a runtime lookup table (token_table.
// generated.inc below), so the set of values a variable of this type may
// hold is every uint16_t, not the set spelled out here - an enum class
// would claim otherwise and clang-tidy's cppcoreguidelines-use-enum-class /
// performance-enum-size would flag the previous enum form the same way
// prop_ids.generated.h already records for prop_id.
//
// APPEND-ONLY, per themes/token_ids.lock (design.md section 5.7.7 /
// section 5.8 decision 4, the same ABI-numbering rule props/prop_ids.lock
// already enforces for prop_id).
using dg_token_id = std::uint16_t;

// Reserved. A lookup returning this id means "no such token".
inline constexpr dg_token_id DG_TOKEN_INVALID = 0;

// -- color -------------------------------------------------------
// The default background a panel/window paints - NodeStyle::fill's usual source.
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_SURFACE = 1;  // "color.surface"
// Text/icon colour painted on top of color.surface.
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_ON_SURFACE = 2;  // "color.on-surface"
// The default border colour for a framed panel.
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_BORDER = 3;  // "color.border"
// The accent colour for a primary action (a button's fill, say).
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_PRIMARY = 4;  // "color.primary"
// Text/icon colour painted on top of color.primary.
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_ON_PRIMARY = 5;  // "color.on-primary"
// color.primary's hovered state - a distinct token per section 5.11.4, not an alpha expression.
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_PRIMARY_HOVER = 6;  // "color.primary-hover"
// color.primary's pressed state - a distinct token per section 5.11.4, not an alpha expression.
// type=color
inline constexpr dg_token_id DG_TOKEN_COLOR_PRIMARY_PRESSED = 7;  // "color.primary-pressed"

// -- radius ------------------------------------------------------
// A small corner radius - chips, small controls.
// type=int
inline constexpr dg_token_id DG_TOKEN_RADIUS_SM = 8;  // "radius.sm"
// The default corner radius for a panel or a button.
// type=int
inline constexpr dg_token_id DG_TOKEN_RADIUS_MD = 9;  // "radius.md"

// -- space -------------------------------------------------------
// A small spacing unit - tight gaps, small padding.
// type=int
inline constexpr dg_token_id DG_TOKEN_SPACE_SM = 10;  // "space.sm"
// The default spacing unit - ordinary gaps and padding.
// type=int
inline constexpr dg_token_id DG_TOKEN_SPACE_MD = 11;  // "space.md"

inline constexpr std::uint16_t kDgTokenMaxId = 11;
inline constexpr std::uint16_t kDgTokenCount = 11;
