// ==========================================================================
// DO NOT EDIT - generated by tools/gen_shortcuts.py from input/shortcuts.toml.
//
// Edit input/shortcuts.toml and re-run:
//     python3 tools/gen_shortcuts.py
// `python3 tools/gen_shortcuts.py --check` fails when this file has drifted.
// ==========================================================================

#pragma once

#include <cstdint>

// The routing-level scopes design.md section 5.5.2 names, GENERATED from
// exactly the `scope` values input/shortcuts.toml's actions reference -
// the same "no speculative vocabulary" policy LogicalKey follows above.
// A closed, internal set (never crosses the C ABI as a raw number), so
// this is a real `enum class`, not a plain-constant family like
// dg_action_id.
namespace dg {

enum class ActionScope : std::uint8_t {
  kApp,
  kTextField,
};

}  // namespace dg
