// ==========================================================================
// DO NOT EDIT - generated by tools/gen_shortcuts.py from input/shortcuts.toml.
//
// Edit input/shortcuts.toml and re-run:
//     python3 tools/gen_shortcuts.py
// `python3 tools/gen_shortcuts.py --check` fails when this file has drifted.
// ==========================================================================

#pragma once

#include <cstdint>

// Shortcut/intent action identifiers - the same shape as dg_prop_id and
// dg_token_id (design.md section 5.5.3: action_id is "同源同构" with
// prop_id/token_id) and for the identical reason: PLAIN CONSTANTS, NOT AN
// ENUMERATION. An action_id will cross the C ABI once 8-3d wires
// dg_app_bind_shortcut/dg_node_scope_action into abi/drawgui.def.toml, so
// the set of values a variable of this type may hold is every uint16_t a
// host may pass in, not the set spelled out here - an enum class would
// claim otherwise, exactly the reasoning prop_ids.generated.h and
// token_ids.generated.h already record for their own families.
//
// APPEND-ONLY, per input/action_ids.lock (design.md section 5.5.3, the
// same ABI-numbering rule props/prop_ids.lock and themes/token_ids.lock
// already enforce for prop_id/token_id).
using dg_action_id = std::uint16_t;

// Reserved. Names "no such action" the way DG_PROP_INVALID/DG_TOKEN_INVALID do.
inline constexpr dg_action_id DG_ACTION_INVALID = 0;

// Copy the current selection to the clipboard.
// scope=text_field consumer="8-4 clipboard"
inline constexpr dg_action_id DG_ACTION_COPY = 1;  // "Mod+C"

// Cut the current selection to the clipboard.
// scope=text_field consumer="8-4 clipboard"
inline constexpr dg_action_id DG_ACTION_CUT = 2;  // "Mod+X"

// Paste the clipboard's text at the caret.
// scope=text_field consumer="8-4 clipboard"
inline constexpr dg_action_id DG_ACTION_PASTE = 3;  // "Mod+V"

// Select the field's entire text.
// scope=text_field consumer="8-4 clipboard + TextField"
inline constexpr dg_action_id DG_ACTION_SELECT_ALL = 4;  // "Mod+A"

// Scroll the target scrollable up by one page.
// scope=app consumer="8-3c keyboard scrolling"
inline constexpr dg_action_id DG_ACTION_SCROLL_PAGE_UP = 5;  // "PageUp"

// Scroll the target scrollable down by one page.
// scope=app consumer="8-3c keyboard scrolling"
inline constexpr dg_action_id DG_ACTION_SCROLL_PAGE_DOWN = 6;  // "PageDown"

// Scroll the target scrollable to its content start.
// scope=app consumer="8-3c keyboard scrolling"
inline constexpr dg_action_id DG_ACTION_SCROLL_TO_START = 7;  // "Home"

// Scroll the target scrollable to its content end.
// scope=app consumer="8-3c keyboard scrolling"
inline constexpr dg_action_id DG_ACTION_SCROLL_TO_END = 8;  // "End"

inline constexpr std::uint16_t kDgActionMaxId = 8;
inline constexpr std::uint16_t kDgActionCount = 8;
