// ==========================================================================
// DO NOT EDIT - generated by tools/gen_shortcuts.py from input/shortcuts.toml.
//
// Edit input/shortcuts.toml and re-run:
//     python3 tools/gen_shortcuts.py
// `python3 tools/gen_shortcuts.py --check` fails when this file has drifted.
// ==========================================================================

#pragma once

#include <cstdint>

// The closed set of physical/logical keys a shortcut binding in
// input/shortcuts.toml actually references - GENERATED, unlike
// dg_action_id above, because this is the opposite ABI shape: a
// LogicalKey is produced internally (the platform layer mapping an SDL
// keysym, once 8-2 exists) and never arrives as an arbitrary
// host-supplied number, so it stays a real `enum class` with an
// EXHAUSTIVE-SWITCH contract - the same shape dg::Key, dg::WidgetKind
// and dg::PointerAction already have, and for the identical reason
// dg::Key's own comment gives: an enumerator naming a key nothing binds
// is a promise this engine does not keep. This is NOT dg::Key
// (include/drawgui/window/window_manager.h) - design.md section 5.5.2 is
// explicit that a text-editing key is not a shortcut; they route at
// different levels and this project does not unify them.
namespace dg {

enum class LogicalKey : std::uint16_t {
  kInvalid = 0,
  kA,
  kC,
  kEnd,
  kHome,
  kPageDown,
  kPageUp,
  kV,
  kX,
};

inline constexpr std::uint16_t kLogicalKeyCount = 8;

}  // namespace dg
