/*
 ==========================================================================
 DO NOT EDIT - generated by tools/gen_abi.py from abi/drawgui.def.toml.

 Edit abi/drawgui.def.toml and re-run:
     python3 tools/gen_abi.py
 `python3 tools/gen_abi.py --check` fails when this file has drifted.
 ==========================================================================
*/

#ifndef DRAWGUI_ABI_DRAWGUI_H
#define DRAWGUI_ABI_DRAWGUI_H

/* A pure C89-compatible header. No C++ type, no Skia type, and no
 * RenderObject/Layer-tree type appears anywhere below - design.md
 * section 5.8's own design principle ("only export the necessary
 * surface"). examples/19_c_client is compiled as C specifically to
 * prove this file never quietly grows a C++ leak. */

#include <stddef.h>
#include <stdint.h>

#if defined(_WIN32) && defined(DG_ABI_BUILD_SHARED)
#define DG_EXPORT __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
#define DG_EXPORT __attribute__((visibility("default")))
#else
#define DG_EXPORT
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* MAJOR<<16 | MINOR. Current build: 0.1
 * (design.md section 5.8 decision 4). Compare dg_abi_version() against
 * this at link time if the two might disagree (a plugin scenario);
 * this project's own examples do not, because they always link the
 * library they were built against. */
#define DG_ABI_VERSION_MAJOR 0u
#define DG_ABI_VERSION_MINOR 1u

/* -- Opaque handle types --------------------------------------------------- */

/* One drawgui application: the window manager and every window/node arena it */
/* owns. */
typedef struct dg_app_s dg_app_t;

/* One OS window and the layout/render/widget state painted into it. */
typedef struct dg_window_s dg_window_t;

/* One layout/render node - pending (not yet in a tree) or live (attached under */
/* a window). */
typedef struct dg_node_s dg_node_t;

/* 7-6: one loaded theme (a token->value table plus, optionally, the untrusted */
/* package directory it came from), owned by the app that loaded it. */
typedef struct dg_theme_s dg_theme_t;

/* -- Structs --------------------------------------------------------------- */

/* One property value, tagged - the ABI's dg::PropValue (node_props.h). */
typedef struct dg_value {
  /* sizeof(dg_value). */
  uint32_t size;
  /* DG_VALUE_* - which field below is meaningful. */
  uint32_t type;
  /* meaningful for DG_VALUE_FLOAT / DG_VALUE_LENGTH. */
  float number;
  /* ARGB for DG_VALUE_COLOR, ordinal for DG_VALUE_ENUM. */
  uint32_t bits;
} dg_value;

/* Reserved for future app-level options. Empty today; `size` alone makes it */
/* extensible. */
typedef struct dg_app_opts {
  /* sizeof(dg_app_opts). */
  uint32_t size;
} dg_app_opts;

/* What a window should be when it appears - dg::WindowSpec at the ABI boundary. */
typedef struct dg_window_opts {
  /* sizeof(dg_window_opts). */
  uint32_t size;
  /* copied at dg_window_create() time; not retained. */
  const char* title;
  /* initial width in device pixels. */
  int32_t width;
  /* initial height in device pixels. */
  int32_t height;
  /* 0xAARRGGBB fill until the first frame paints. */
  uint32_t background_argb;
} dg_window_opts;

/* One entry of dg_poll_events() - the C shape of dg::PumpResult, flattened to */
/* one kind at a time. */
typedef struct dg_event {
  /* sizeof(dg_event). */
  uint32_t size;
  /* DG_EVENT_*. */
  uint32_t kind;
  /* which window this event is about. */
  dg_window_t* window;
  /* DG_EVENT_CLICK only; null otherwise. */
  dg_node_t* node;
  /* DG_EVENT_CLICK only: the pointer position, device pixels. */
  int32_t x;
  /* DG_EVENT_CLICK only: the pointer position, device pixels. */
  int32_t y;
} dg_event;

/* 7-6: out-param naming why dg_theme_load_dir()/dg_theme_load_memory() failed. */
/* The human-readable detail (a JSON key path or a byte offset) is */
/* dg_last_error(), matching every other failing call in this ABI; this struct */
/* carries only the machine-checkable status, so a host can branch on it without */
/* string-parsing dg_last_error()'s text. */
typedef struct dg_theme_err {
  /* sizeof(dg_theme_err). */
  uint32_t size;
  /* DG_THEME_ERR_* - mirrors dg::ThemeLoadStatus. */
  uint32_t status;
} dg_theme_err;

/* -- Constants ------------------------------------------------------------- */

/* dg_node_create()'s type_id - the minimum vocabulary the acceptance criterion */
/* needs. */
/* A plain, non-interactive leaf (WidgetKind::kPanel). */
#define DG_NODE_TYPE_BOX 1u
/* A clickable leaf (WidgetKind::kButton): hover/press/click, three fills. */
#define DG_NODE_TYPE_BUTTON 2u

/* dg_value::type. */
/* PropType::k_float. */
#define DG_VALUE_FLOAT 1u
/* PropType::k_length. */
#define DG_VALUE_LENGTH 2u
/* PropType::k_color. */
#define DG_VALUE_COLOR 3u
/* PropType::k_enum. */
#define DG_VALUE_ENUM 4u
/* 7-6: bits names a token_id (themes/schema.toml). dg_node_set_prop() with this */
/* type calls dg::bind_token() instead of a literal write - the ABI's own */
/* instance of design.md section 5.7.2's $token live reference, reusing */
/* dg_node_set_prop() unchanged rather than adding a second, bind-shaped */
/* function. */
#define DG_VALUE_TOKEN 5u

/* dg_event::kind. */
/* The window closed (user or dg_debug_ script); the dg_window_t handle is now */
/* stale. */
#define DG_EVENT_WINDOW_CLOSED 1u
/* A press and its release landed on the same node - */
/* dg::InteractionChange::clicked. */
#define DG_EVENT_CLICK 2u

/* Every dg_*() status-returning function's result. */
/* Success. */
#define DG_ERR_OK 0
/* std::bad_alloc crossed the boundary; caught, never propagated (design.md */
/* section 5.17.1). */
#define DG_ERR_OOM (-1)
/* Any other C++ exception crossed the boundary; caught, never propagated. */
/* dg_last_error() names it. */
#define DG_ERR_INTERNAL (-2)
/* A required pointer argument was null, or an out-param buffer size was */
/* invalid. */
#define DG_ERR_INVALID_ARGUMENT (-3)
/* The handle names no live resource - never attached, already */
/* removed/destroyed, or wrong app (design.md section 5.17.2). */
#define DG_ERR_INVALID_HANDLE (-4)
/* prop_id/type_id names nothing the generated table defines - */
/* dg::PropStatus::kUnknownId. */
#define DG_ERR_UNKNOWN_ID (-5)
/* dg_value::type disagrees with the property's declared type - */
/* dg::PropStatus::kTypeMismatch. */
#define DG_ERR_TYPE_MISMATCH (-6)
/* dg::PropStatus::kValueOutOfRange. */
#define DG_ERR_VALUE_OUT_OF_RANGE (-7)
/* dg::PropStatus::kNotApplicable (design.md section 5.8 decision 7's parentData */
/* case included). */
#define DG_ERR_NOT_APPLICABLE (-8)
/* dg::PropStatus::kUnsupported, or an ABI operation this slice never */
/* implemented (a non-null dg_node_insert_before ref). */
#define DG_ERR_UNSUPPORTED (-9)
/* dg_node_insert_before()/dg_window_set_root() on a node that is already live */
/* in a tree. */
#define DG_ERR_ALREADY_ATTACHED (-10)
/* An operation needs a node to be live under a window, and it is still pending. */
#define DG_ERR_NO_WINDOW (-11)
/* 7-6: dg_node_set_prop() with a DG_VALUE_TOKEN value, but dg_app_set_theme() */
/* was never called for this node's app - there is no theme to resolve the token */
/* against yet. */
#define DG_ERR_NO_ACTIVE_THEME (-12)

/* 7-6: dg_theme_err::status, mirroring dg::ThemeLoadStatus */
/* (include/drawgui/theme/theme_loader.h) one-to-one. */
/* ThemeLoadStatus::kParseError - malformed JSON; dg_last_error() carries the */
/* byte offset. */
#define DG_THEME_ERR_PARSE_ERROR 1u
/* ThemeLoadStatus::kMissingField. */
#define DG_THEME_ERR_MISSING_FIELD 2u
/* ThemeLoadStatus::kUnknownToken - dg_last_error() names the exact JSON key */
/* path (design.md section 5.7.5). */
#define DG_THEME_ERR_UNKNOWN_TOKEN 3u
/* ThemeLoadStatus::kTypeMismatch. */
#define DG_THEME_ERR_TYPE_MISMATCH 4u
/* ThemeLoadStatus::kUnsupportedSchemaVersion - design.md section 12 open */
/* question 7's settled reject-old policy. */
#define DG_THEME_ERR_UNSUPPORTED_SCHEMA_VERSION 5u
/* ThemeLoadStatus::kIoError - theme.json or a resource file could not be read */
/* (missing, not a regular file, a symlink loop). */
#define DG_THEME_ERR_IO_ERROR 6u
/* ThemeLoadStatus::kPathTraversal - design.md section 5.7.5's restriction; a */
/* resolved path escaped the package root. */
#define DG_THEME_ERR_PATH_TRAVERSAL 7u
/* ThemeLoadStatus::kResourceTooLarge - a single file exceeded its size bound. */
#define DG_THEME_ERR_RESOURCE_TOO_LARGE 8u
/* ThemeLoadStatus::kTooManyResources - the resource tree exceeded a file-count */
/* or aggregate-size bound. */
#define DG_THEME_ERR_TOO_MANY_RESOURCES 9u

/* -- Property ids (props/drawgui.props.toml) ------------------------------ */

/* Re-emitted here in C-compatible #define form from the SAME validated
 * props/drawgui.props.toml tools/gen_props.py already generates
 * include/drawgui/render/prop_ids.generated.h from (an `inline constexpr`
 * C++ form this header cannot use). One source of truth, two renderings -
 * design.md section 5.8 decision 5.
 *
 * #ifndef __cplusplus GUARDS THE WHOLE BLOCK, and that is load-bearing,
 * not decorative: prop_ids.generated.h ALSO declares `DG_PROP_WIDTH` and
 * every other name below, as an `inline constexpr dg_prop_id`, not a
 * macro. A #define of the identical name would silently rewrite THAT
 * declaration wherever both headers reach the same C++ translation unit
 * (src/abi/abi_impl.cpp does, needing node_props.h for dg::set_prop()) -
 * measured, not guessed: an earlier version of this generator produced
 * exactly `inline constexpr dg_prop_id 1 = 1;` there. A pure C consumer
 * never includes prop_ids.generated.h (it is not a C header at all), so
 * excluding these constants from C++ costs a C++ caller nothing it had
 * another way to get, and the guard is checkable by the one thing that
 * actually exercises it: examples/19_c_client compiles as C. */

#ifndef __cplusplus

typedef uint16_t dg_prop_id;
#define DG_PROP_INVALID 0

/* Border-box width; absent means shrink-to-fit. */
#define DG_PROP_WIDTH 1
/* Border-box height; absent means shrink-to-fit. */
#define DG_PROP_HEIGHT 2
/* Lower clamp applied after the size source resolves. */
#define DG_PROP_MIN_WIDTH 3
/* Upper clamp applied after the size source resolves. */
#define DG_PROP_MAX_WIDTH 4
/* Lower clamp applied after the size source resolves. */
#define DG_PROP_MIN_HEIGHT 5
/* Upper clamp applied after the size source resolves. */
#define DG_PROP_MAX_HEIGHT 6
/* width/height; derives the second dimension from the first. */
#define DG_PROP_ASPECT_RATIO 7
/* Left padding; shrinks the constraint passed to children. */
#define DG_PROP_PADDING_L 8
/* Top padding; shrinks the constraint passed to children. */
#define DG_PROP_PADDING_T 9
/* Right padding; shrinks the constraint passed to children. */
#define DG_PROP_PADDING_R 10
/* Bottom padding; shrinks the constraint passed to children. */
#define DG_PROP_PADDING_B 11
/* Left outer spacing applied by the parent, excluded from size. */
#define DG_PROP_MARGIN_L 12
/* Top outer spacing applied by the parent, excluded from size. */
#define DG_PROP_MARGIN_T 13
/* Right outer spacing applied by the parent, excluded from size. */
#define DG_PROP_MARGIN_R 14
/* Bottom outer spacing applied by the parent, excluded from size. */
#define DG_PROP_MARGIN_B 15
/* Border-box fill, 0xAARRGGBB unpremultiplied. */
#define DG_PROP_BACKGROUND_COLOR 16
/* Linear/radial/sweep gradient fill; dedicated setter, not a scalar. */
#define DG_PROP_BACKGROUND_GRADIENT 17
/* Left border thickness, inside the border box. */
#define DG_PROP_BORDER_WIDTH_L 18
/* Top border thickness, inside the border box. */
#define DG_PROP_BORDER_WIDTH_T 19
/* Right border thickness, inside the border box. */
#define DG_PROP_BORDER_WIDTH_R 20
/* Bottom border thickness, inside the border box. */
#define DG_PROP_BORDER_WIDTH_B 21
/* Colour of all four borders, 0xAARRGGBB unpremultiplied. */
#define DG_PROP_BORDER_COLOR 22
/* Top-left corner radius; clips every decoration layer. */
#define DG_PROP_BORDER_RADIUS_TL 23
/* Top-right corner radius; clips every decoration layer. */
#define DG_PROP_BORDER_RADIUS_TR 24
/* Bottom-right corner radius; clips every decoration layer. */
#define DG_PROP_BORDER_RADIUS_BR 25
/* Bottom-left corner radius; clips every decoration layer. */
#define DG_PROP_BORDER_RADIUS_BL 26
/* 0..1 subtree alpha; below 1 forces a compositing layer. */
#define DG_PROP_OPACITY 27
/* Outer shadow (offset/blur/spread/colour); dedicated setter. */
#define DG_PROP_SHADOW 28
/* Whether content beyond the border box is clipped. */
#define DG_PROP_OVERFLOW 29
/* Decomposed translate/scale/rotate plus origin, for interpolation. */
#define DG_PROP_TRANSFORM 30
/* Main axis orientation and ordering. */
#define DG_PROP_DIRECTION 31
/* Distribution of free space along the main axis. */
#define DG_PROP_JUSTIFY 32
/* Cross-axis alignment of children within a line. */
#define DG_PROP_ALIGN 33
/* Main-axis spacing between adjacent children; adds to margins. */
#define DG_PROP_GAP 34
/* Whether the container hugs its content or fills the main axis. */
#define DG_PROP_MAIN_SIZE 35
/* Spacing between wrapped runs; meaningful only on RenderWrap. */
#define DG_PROP_RUN_GAP 36
/* Cross-axis alignment of the run stack; RenderWrap only. */
#define DG_PROP_ALIGN_CONTENT 37
/* Weight for distributing positive free main-axis space. */
#define DG_PROP_GROW 38
/* Weight for absorbing negative free main-axis space. */
#define DG_PROP_SHRINK 39
/* Main-axis base size; absent means the child's natural size. */
#define DG_PROP_BASIS 40
/* Per-child override of the container's cross-axis align. */
#define DG_PROP_ALIGN_SELF 41
/* Inset from the stack content box; setting it positions the child. */
#define DG_PROP_LEFT 42
/* Inset from the stack content box; setting it positions the child. */
#define DG_PROP_TOP 43
/* Inset from the stack content box; setting it positions the child. */
#define DG_PROP_RIGHT 44
/* Inset from the stack content box; setting it positions the child. */
#define DG_PROP_BOTTOM 45
/* Which axis, if any, this node hands its child an unbounded constraint on. */
#define DG_PROP_SCROLL_AXIS 46
/* Which decoded ImageCatalog entry to paint; dedicated setter, not a scalar. */
#define DG_PROP_IMAGE_SOURCE 47
/* How a decoded bitmap is scaled to the node's bounds. */
#define DG_PROP_IMAGE_FIT 48
/* Painted in place of the image while none is decoded yet; never a hole. */
#define DG_PROP_IMAGE_PLACEHOLDER_COLOR 49

#endif /* !__cplusplus */

/* -- Theme token ids (themes/schema.toml) ------------------------ */

/* 7-6: re-emitted here in C-compatible #define form from the SAME
 * validated themes/schema.toml tools/gen_theme.py already generates
 * include/drawgui/theme/token_ids.generated.h from - design.md section 5.7.7's
 * own "主题 token_id 与 prop_id 同源同构" decision, applied at 7-6 the same
 * way decision 5 already applies to prop_id above. Same #ifndef __cplusplus
 * guard, same reason: token_ids.generated.h ALSO declares DG_TOKEN_* as an
 * `inline constexpr dg_token_id`, not a macro. */

#ifndef __cplusplus

typedef uint16_t dg_token_id;
#define DG_TOKEN_INVALID 0

/* The default background a panel/window paints - NodeStyle::fill's usual */
/* source. */
#define DG_TOKEN_COLOR_SURFACE 1
/* Text/icon colour painted on top of color.surface. */
#define DG_TOKEN_COLOR_ON_SURFACE 2
/* The default border colour for a framed panel. */
#define DG_TOKEN_COLOR_BORDER 3
/* The accent colour for a primary action (a button's fill, say). */
#define DG_TOKEN_COLOR_PRIMARY 4
/* Text/icon colour painted on top of color.primary. */
#define DG_TOKEN_COLOR_ON_PRIMARY 5
/* color.primary's hovered state - a distinct token per section 5.11.4, not an */
/* alpha expression. */
#define DG_TOKEN_COLOR_PRIMARY_HOVER 6
/* color.primary's pressed state - a distinct token per section 5.11.4, not an */
/* alpha expression. */
#define DG_TOKEN_COLOR_PRIMARY_PRESSED 7
/* A small corner radius - chips, small controls. */
#define DG_TOKEN_RADIUS_SM 8
/* The default corner radius for a panel or a button. */
#define DG_TOKEN_RADIUS_MD 9
/* A small spacing unit - tight gaps, small padding. */
#define DG_TOKEN_SPACE_SM 10
/* The default spacing unit - ordinary gaps and padding. */
#define DG_TOKEN_SPACE_MD 11
/* The keyboard focus indicator (7-4) - a visible ring outset around whichever */
/* widget dg::Focus currently names, read directly via Theme::color_value() */
/* rather than through a $token live binding (doc/focus.md section 5: the ring */
/* is paint/positioning state with no LayoutTree node of its own, the same shape */
/* TextField's caret/selection_highlight already are). */
#define DG_TOKEN_COLOR_FOCUS_RING 12

#endif /* !__cplusplus */

/* -- Functions ------------------------------------------------------------- */

/* MAJOR<<16 | MINOR - design.md section 5.8's own dg_abi_version() line. */
DG_EXPORT uint32_t dg_abi_version(void);

/* Starts the window manager. `opts` may be null (defaults). */
DG_EXPORT dg_app_t* dg_app_create(const dg_app_opts* opts);

/* Closes every open window and shuts the platform down. `app` is stale */
/* afterwards. */
DG_EXPORT void dg_app_destroy(dg_app_t* app);

/* Opens one window immediately, filled with opts->background_argb until the */
/* first frame paints. */
DG_EXPORT dg_window_t* dg_window_create(dg_app_t* app, const dg_window_opts* opts);

/* Attaches `node` (must be pending) under window's tree as its sole content */
/* root. */
DG_EXPORT int32_t dg_window_set_root(dg_window_t* window, dg_node_t* node);

/* Allocates a PENDING node - not yet part of any window's tree. See */
/* DG_NODE_TYPE_*. */
DG_EXPORT dg_node_t* dg_node_create(dg_app_t* app, uint16_t type_id);

/* dg::set_prop() at the ABI boundary. Works on pending or live nodes. */
DG_EXPORT int32_t dg_node_set_prop(dg_node_t* node, uint16_t prop_id, const dg_value* value);

/* Attaches pending `child` under live `parent`. `ref` must be null this slice */
/* (append-only; see doc/abi.md section 5). */
DG_EXPORT int32_t dg_node_insert_before(dg_node_t* parent, dg_node_t* child, dg_node_t* ref);

/* Invalidates the handle (DG_ERR_INVALID_HANDLE on every later call). Does not */
/* detach a live node's tree structure - see doc/abi.md section 5. */
DG_EXPORT int32_t dg_node_remove(dg_node_t* node);

/* Blocks up to timeout_ms (negative: forever), pumps every window, returns the */
/* number of events now pollable. */
DG_EXPORT int32_t dg_wait_events(dg_app_t* app, int32_t timeout_ms);

/* Dequeues up to max events into out[]. Never blocks. Returns the number */
/* copied. */
DG_EXPORT int32_t dg_poll_events(dg_app_t* app, dg_event* out, int32_t max);

/* The message from the most recent failing call on this thread. Valid until the */
/* next drawgui call on it. */
DG_EXPORT const char* dg_last_error(void);

/* This node's subtree as JSON (type/bounds/parentData). See doc/abi.md section */
/* 7 for exactly what is and is not included. */
DG_EXPORT const char* dg_dump_layout_tree(dg_node_t* node);

/* 7-6: loads an EXTERNAL, untrusted theme package directory (design.md section */
/* 5.7.4/5.7.5 via dg::ThemePackage) - path traversal/size/resource-count bounds */
/* all apply. `err` may be null; on failure it (if non-null) and dg_last_error() */
/* both describe why. */
DG_EXPORT dg_theme_t* dg_theme_load_dir(dg_app_t* app, const char* dir, dg_theme_err* err);

/* 7-6: loads a theme from an in-memory JSON blob the host already has. */
/* `base_dir`, if non-null, is opened as a dg::ThemePackage resource root (the */
/* same path-traversal surface dg_theme_load_dir() has) so resource reads still */
/* resolve safely; null means no resource access for this theme. */
DG_EXPORT dg_theme_t* dg_theme_load_memory(dg_app_t* app, const char* json, uint32_t len,
                                           const char* base_dir, dg_theme_err* err);

/* 7-6: "light" or "dark" (design.md section 5.7.2). If this theme is its app's */
/* currently active one, every window's bound nodes re-resolve immediately - no */
/* widget tree rebuild (design.md section 5.7.6). */
DG_EXPORT int32_t dg_theme_set_variant(dg_theme_t* theme, const char* variant);

/* 7-6: patches one token's value in-place (the token's own scalar type is */
/* always DG_VALUE_COLOR or DG_VALUE_FLOAT/DG_VALUE_LENGTH - never a */
/* dedicated-setter shape, since every theme token is scalar by design.md */
/* section 5.7.2's own two-way dichotomy). A color token is overridden under the */
/* theme's CURRENTLY ACTIVE variant. Live-updates bound nodes exactly like */
/* dg_theme_set_variant(). */
DG_EXPORT int32_t dg_theme_override(dg_theme_t* theme, uint16_t token_id,
                                    const dg_value* value);

/* 7-6: makes `theme` this app's active theme and immediately re-applies every */
/* window's ThemeBindings against it - this IS hot reload's second half: reload */
/* with dg_theme_load_dir()/load_memory() again, then call this again with the */
/* fresh handle (design.md section 5.7.6, settled in doc/theme-packages.md). */
DG_EXPORT int32_t dg_app_set_theme(dg_app_t* app, dg_theme_t* theme);

/* TEST-ONLY. WindowManager::warp_pointer() at the ABI boundary - see the file */
/* header. */
DG_EXPORT int32_t dg_debug_warp_pointer(dg_window_t* window, int32_t x, int32_t y);

/* TEST-ONLY. WindowManager::post_pointer_button() at the ABI boundary - see the */
/* file header. */
DG_EXPORT int32_t dg_debug_post_pointer_button(dg_window_t* window, int32_t down, int32_t x,
                                               int32_t y);

/* TEST-ONLY. Unconditionally throws (1=bad_alloc, 2=runtime_error, else an int) */
/* - the exception-boundary test's own fault injector. */
DG_EXPORT int32_t dg_debug_trigger_exception(int32_t kind);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* DRAWGUI_ABI_DRAWGUI_H */
