// ==========================================================================
// DO NOT EDIT - generated by tools/gen_abi.py from abi/drawgui.def.toml.
//
// Ambient ABI declarations for a future Bun/Node FFI binding (design.md
// section 6, phase P6). NOTHING in this project's own build reads this
// file yet - there is no JS framework layer to bind through - so treat
// it as a settled TARGET shape rather than a proven one; doc/abi.md
// section 6 records that scoping decision explicitly.
// ==========================================================================

// One drawgui application: the window manager and every window/node arena it
// owns.
export type dg_app_t = unknown;

// One OS window and the layout/render/widget state painted into it.
export type dg_window_t = unknown;

// One layout/render node - pending (not yet in a tree) or live (attached under
// a window).
export type dg_node_t = unknown;

// 7-6: one loaded theme (a token->value table plus, optionally, the untrusted
// package directory it came from), owned by the app that loaded it.
export type dg_theme_t = unknown;

// One property value, tagged - the ABI's dg::PropValue (node_props.h).
export interface dg_value {
  size: number;
  type: number;
  number: number;
  bits: number;
}

// Reserved for future app-level options. Empty today; `size` alone makes it
// extensible.
export interface dg_app_opts {
  size: number;
}

// What a window should be when it appears - dg::WindowSpec at the ABI boundary.
export interface dg_window_opts {
  size: number;
  title: string | null;
  width: number;
  height: number;
  background_argb: number;
}

// One entry of dg_poll_events() - the C shape of dg::PumpResult, flattened to
// one kind at a time.
export interface dg_event {
  size: number;
  kind: number;
  window: dg_window_t | null;
  node: dg_node_t | null;
  x: number;
  y: number;
  action_id: number;
}

// 7-6: out-param naming why dg_theme_load_dir()/dg_theme_load_memory() failed.
// The human-readable detail (a JSON key path or a byte offset) is
// dg_last_error(), matching every other failing call in this ABI; this struct
// carries only the machine-checkable status, so a host can branch on it without
// string-parsing dg_last_error()'s text.
export interface dg_theme_err {
  size: number;
  status: number;
}

// dg_node_create()'s type_id - the minimum vocabulary the acceptance criterion
// needs.
export const node_type = {
  BOX: 1,
  BUTTON: 2,
} as const;

// dg_value::type.
export const value_type = {
  FLOAT: 1,
  LENGTH: 2,
  COLOR: 3,
  ENUM: 4,
  TOKEN: 5,
} as const;

// dg_event::kind.
export const event_kind = {
  WINDOW_CLOSED: 1,
  CLICK: 2,
  ACTION: 3,
} as const;

// Every dg_*() status-returning function's result.
export const error = {
  OK: 0,
  OOM: -1,
  INTERNAL: -2,
  INVALID_ARGUMENT: -3,
  INVALID_HANDLE: -4,
  UNKNOWN_ID: -5,
  TYPE_MISMATCH: -6,
  VALUE_OUT_OF_RANGE: -7,
  NOT_APPLICABLE: -8,
  UNSUPPORTED: -9,
  ALREADY_ATTACHED: -10,
  NO_WINDOW: -11,
  NO_ACTIVE_THEME: -12,
} as const;

// 7-6: dg_theme_err::status, mirroring dg::ThemeLoadStatus
// (include/drawgui/theme/theme_loader.h) one-to-one.
export const theme_err = {
  PARSE_ERROR: 1,
  MISSING_FIELD: 2,
  UNKNOWN_TOKEN: 3,
  TYPE_MISMATCH: 4,
  UNSUPPORTED_SCHEMA_VERSION: 5,
  IO_ERROR: 6,
  PATH_TRAVERSAL: 7,
  RESOURCE_TOO_LARGE: 8,
  TOO_MANY_RESOURCES: 9,
} as const;

// Property ids - props/drawgui.props.toml, re-emitted (see gen_abi.py).
export const prop = {
  width: 1,
  height: 2,
  min_width: 3,
  max_width: 4,
  min_height: 5,
  max_height: 6,
  aspect_ratio: 7,
  padding_l: 8,
  padding_t: 9,
  padding_r: 10,
  padding_b: 11,
  margin_l: 12,
  margin_t: 13,
  margin_r: 14,
  margin_b: 15,
  background_color: 16,
  background_gradient: 17,
  border_width_l: 18,
  border_width_t: 19,
  border_width_r: 20,
  border_width_b: 21,
  border_color: 22,
  border_radius_tl: 23,
  border_radius_tr: 24,
  border_radius_br: 25,
  border_radius_bl: 26,
  opacity: 27,
  shadow: 28,
  overflow: 29,
  transform: 30,
  direction: 31,
  justify: 32,
  align: 33,
  gap: 34,
  main_size: 35,
  run_gap: 36,
  align_content: 37,
  grow: 38,
  shrink: 39,
  basis: 40,
  align_self: 41,
  left: 42,
  top: 43,
  right: 44,
  bottom: 45,
  scroll_axis: 46,
  image_source: 47,
  image_fit: 48,
  image_placeholder_color: 49,
} as const;

// Token ids (7-6) - themes/schema.toml, re-emitted (see gen_abi.py).
export const token = {
  'color.surface': 1,
  'color.on-surface': 2,
  'color.border': 3,
  'color.primary': 4,
  'color.on-primary': 5,
  'color.primary-hover': 6,
  'color.primary-pressed': 7,
  'radius.sm': 8,
  'radius.md': 9,
  'space.sm': 10,
  'space.md': 11,
  'color.focus-ring': 12,
} as const;

export declare namespace DrawguiAbi {
  // MAJOR<<16 | MINOR - design.md section 5.8's own dg_abi_version() line.
  function dg_abi_version(): number;
  // Starts the window manager. `opts` may be null (defaults).
  function dg_app_create(opts: dg_app_opts): dg_app_t | null;
  // Closes every open window and shuts the platform down. `app` is stale
  // afterwards.
  function dg_app_destroy(app: dg_app_t | null): void;
  // Opens one window immediately, filled with opts->background_argb until the
  // first frame paints.
  function dg_window_create(app: dg_app_t | null, opts: dg_window_opts): dg_window_t | null;
  // Attaches `node` (must be pending) under window's tree as its sole content
  // root.
  function dg_window_set_root(window: dg_window_t | null, node: dg_node_t | null): number;
  // Allocates a PENDING node - not yet part of any window's tree. See
  // DG_NODE_TYPE_*.
  function dg_node_create(app: dg_app_t | null, type_id: number): dg_node_t | null;
  // dg::set_prop() at the ABI boundary. Works on pending or live nodes.
  function dg_node_set_prop(node: dg_node_t | null, prop_id: number, value: dg_value): number;
  // Attaches pending `child` under live `parent`. `ref` must be null this slice
  // (append-only; see doc/abi.md section 5).
  function dg_node_insert_before(parent: dg_node_t | null, child: dg_node_t | null, ref: dg_node_t | null): number;
  // Invalidates the handle (DG_ERR_INVALID_HANDLE on every later call). Does not
  // detach a live node's tree structure - see doc/abi.md section 5.
  function dg_node_remove(node: dg_node_t | null): number;
  // 8-3d: declares that `node` consumes `action_id` (design.md section 5.5.3) -
  // wraps dg::ActionScopes::scope() unchanged. `node` must be LIVE
  // (DG_ERR_NO_WINDOW otherwise): ActionScopes is keyed by dg::NodeId, which a
  // pending node does not have yet. A no-op, not an error, if `node` already
  // scopes `action_id`.
  function dg_node_scope_action(node: dg_node_t | null, action_id: number): number;
  // 8-3d: the platform accelerator text for `action_id` (e.g. "Ctrl+A"),
  // generated from the SAME binding table dg::shortcut_label() (chord.h,
  // unit-tested since 8-1/8-2) already builds - this wraps it rather than
  // re-implementing label generation. Returns NULL for an action_id no binding
  // names (dg::shortcut_label()'s own std::optional empty case) - see doc/abi.md
  // section 13 for why NULL rather than an empty string. Valid until the next
  // dg_shortcut_label() call on this thread, matching dg_last_error()'s own
  // lifetime rule.
  function dg_shortcut_label(action_id: number): string | null;
  // Blocks up to timeout_ms (negative: forever), pumps every window, returns the
  // number of events now pollable.
  function dg_wait_events(app: dg_app_t | null, timeout_ms: number): number;
  // Dequeues up to max events into out[]. Never blocks. Returns the number
  // copied.
  function dg_poll_events(app: dg_app_t | null, out: dg_event, max: number): number;
  // The message from the most recent failing call on this thread. Valid until the
  // next drawgui call on it.
  function dg_last_error(): string | null;
  // This node's subtree as JSON (type/bounds/parentData). See doc/abi.md section
  // 7 for exactly what is and is not included.
  function dg_dump_layout_tree(node: dg_node_t | null): string | null;
  // 7-6: loads an EXTERNAL, untrusted theme package directory (design.md section
  // 5.7.4/5.7.5 via dg::ThemePackage) - path traversal/size/resource-count bounds
  // all apply. `err` may be null; on failure it (if non-null) and dg_last_error()
  // both describe why.
  function dg_theme_load_dir(app: dg_app_t | null, dir: string | null, err: dg_theme_err): dg_theme_t | null;
  // 7-6: loads a theme from an in-memory JSON blob the host already has.
  // `base_dir`, if non-null, is opened as a dg::ThemePackage resource root (the
  // same path-traversal surface dg_theme_load_dir() has) so resource reads still
  // resolve safely; null means no resource access for this theme.
  function dg_theme_load_memory(app: dg_app_t | null, json: string | null, len: number, base_dir: string | null, err: dg_theme_err): dg_theme_t | null;
  // 7-6: "light" or "dark" (design.md section 5.7.2). If this theme is its app's
  // currently active one, every window's bound nodes re-resolve immediately - no
  // widget tree rebuild (design.md section 5.7.6).
  function dg_theme_set_variant(theme: dg_theme_t | null, variant: string | null): number;
  // 7-6: patches one token's value in-place (the token's own scalar type is
  // always DG_VALUE_COLOR or DG_VALUE_FLOAT/DG_VALUE_LENGTH - never a
  // dedicated-setter shape, since every theme token is scalar by design.md
  // section 5.7.2's own two-way dichotomy). A color token is overridden under the
  // theme's CURRENTLY ACTIVE variant. Live-updates bound nodes exactly like
  // dg_theme_set_variant().
  function dg_theme_override(theme: dg_theme_t | null, token_id: number, value: dg_value): number;
  // 7-6: makes `theme` this app's active theme and immediately re-applies every
  // window's ThemeBindings against it - this IS hot reload's second half: reload
  // with dg_theme_load_dir()/load_memory() again, then call this again with the
  // fresh handle (design.md section 5.7.6, settled in doc/theme-packages.md).
  function dg_app_set_theme(app: dg_app_t | null, theme: dg_theme_t | null): number;
  // TEST-ONLY. WindowManager::warp_pointer() at the ABI boundary - see the file
  // header.
  function dg_debug_warp_pointer(window: dg_window_t | null, x: number, y: number): number;
  // TEST-ONLY. WindowManager::post_pointer_button() at the ABI boundary - see the
  // file header.
  function dg_debug_post_pointer_button(window: dg_window_t | null, down: number, x: number, y: number): number;
  // TEST-ONLY. WindowManager::post_logical_key() at the ABI boundary, driving a
  // real SDL key event through the real queue exactly as
  // dg_debug_post_pointer_button() does for clicks - see the file header.
  // `logical_key_name` is one bare key name from
  // src/shortcuts/logical_key_table.generated.inc (e.g. "PageUp"), parsed with
  // dg::parse_chord(); a name carrying a modifier ("Mod+C") or one the generated
  // table does not list is DG_ERR_INVALID_ARGUMENT, because post_logical_key()
  // itself has no modifier parameter (the injected event always carries
  // SDL_KMOD_NONE) - this hook exists only to exercise 8-3d's own DG_EVENT_ACTION
  // plumbing over an unmodified app-scope chord (PageUp/PageDown/Home/End), not
  // to simulate arbitrary modified shortcuts headlessly.
  function dg_debug_post_key(window: dg_window_t | null, down: number, logical_key_name: string | null): number;
  // TEST-ONLY. Unconditionally throws (1=bad_alloc, 2=runtime_error, else an int)
  // - the exception-boundary test's own fault injector.
  function dg_debug_trigger_exception(kind: number): number;
}
